import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/app/components/header/Header";
import { ThemeProvider } from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
   children,
  }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body>
    <ThemeProvider>
      <Header />
      {children}
    </ThemeProvider>
    </body>
    </html>
  );
}